name: rhoneCube
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - fftw=3.3.10
  - pip
  - pip:
      - lexcube==0.4.16
      - jupyter[complete]
      - ipykernel==6.29.4
      - jupyter_contrib_nbextensions==0.7.0
      - notebook==7.2.1
      - nbconvert==7.16.4
      - xarray[complete]
      - h5netcdf==1.3.0
      - h5py==3.11.0
      - scipy==1.13.1
      - cython==3.0.10
      - pyfftw==0.13.1
      - matplotlib==3.9.0
      - itables==2.1.2
      - fcwt==0.1.18
      - python-dotenv==1.0.1
      - tqdm==4.66.4
